let allMusic = [
    {
        name : "A Life I Believe",
        artist : "jonworthymusic",
        img : "music-1",
        audio : "music-1",
    },
    {
        name : "Annie",
        artist : "jonworthymusic",
        img : "music-2",
        audio : "music-2",
    },
    {
        name : "Bad Habit",
        artist : "jonworthymusic",
        img : "music-3",
        audio : "music-3",
    },
    {
        name : "Begging For More",
        artist : "jonworthymusic",
        img : "music-4",
        audio : "music-4",
    },
    {
        name : "Better Day",
        artist : "jonworthymusic",
        img : "music-5",
        audio : "music-5",
    },
    {
        name : "By the Water",
        artist : "jonworthymusic",
        img : "music-6",
        audio : "music-6",
    },
    {
        name : "Can't Help But Feel",
        artist : "jonworthymusic",
        img : "music-7",
        audio : "music-7",
    },
    {
        name : "Chasing Dreams",
        artist : "jonworthymusic",
        img : "music-8",
        audio : "music-8",
    },
    {
        name : "Trippy fun",
        artist : "jonworthymusic",
        img : "music-9",
        audio : "music-9",
    },
    {
        name : "Rocksteady",
        artist : "BadaroJambrass",
        img : "music-10",
        audio : "music-10",
    },
    {
        name : "Forever Friends",
        artist : "FancyMoon",
        img : "music-11",
        audio : "music-11",
    },
    {
        name : "FOREVER LOVE",
        artist : "davidtribble",
        img : "music-12",
        audio : "music-12",
    },
    {
        name : "about me",
        artist : "NDA",
        img : "music-13",
        audio : "music-13",
    },
    {
        name : "Need A Light",
        artist : "paradoxhiphop",
        img : "music-14",
        audio : "music-14",
    },
    {
        name : "Good Enough",
        artist : "delirowe",
        img : "music-15",
        audio : "music-15",
    },
    {
        name : "Pallazzine",
        artist : "stan-g",
        img : "music-16",
        audio : "music-16",
    },
    {
        name : "Close To Me",
        artist : "alezz",
        img : "music-17",
        audio : "music-17",
    },
    {
        name : "Kerstin",
        artist : "Slowcruise234",
        img : "music-18",
        audio : "music-18",
    },
    {
        name : "God Out of the Machine",
        artist : "OneManBook",
        img : "music-19",
        audio : "music-19",
    },
    {
        name : "Dark Night of the Soul",
        artist : "OneManBook",
        img : "music-20",
        audio : "music-20",
    }
]